### ISSUE TITLE
Allow different settings for rounding maximized or fullscreen windows

### ISSUE THREAD

**Issue by caetano-m** [yilozt/rounded-window-corners#10]
The option for rounded corners in maximized windows makes fullscreen windows (when you press f11 and the topbar is hidden) rounded too. It would be nice if the fullscreen windows in fact occupied the whole screen, but maximized windows preserved the rounded corners. 

Btw, thank you for this amazing extension!

**Comment by yilozt** [comment]
Implements in #24
