### ISSUE TITLE
Cropped Firefox bug

### ISSUE THREAD

**Issue by jntdofe** [yilozt/rounded-window-corners#100]
![image](https://user-images.githubusercontent.com/73024442/208013341-31f066ab-d51d-4cd8-acfd-6a1e5612f2f9.png)
---
### System:
Fedora 37, Gnome 43.2, Wayland.
Extension version 9.

### Description:
Firefox window appears cropped after accessing "activities".

### How to reproduce:
1. Open Firefox.
2. Maximize Firefox (if already maximized, skip this step).
3. Restore(Unmaximize) Firefox.
4. Open and exit the activities view.

Firefox will appear cropped.
Resizing or maximizing the window restores Firefox to normal.

**Comment by EddoWagt** [comment]
If you use gTile or some similar extension, this will also happen when resizing the window to something smaller. I guess it appears when you decrease the size of the window through some kind of tool.

A way to circumvent the issue is to blacklist Firefox from Rounded Window Corners

**Comment by yilozt** [comment]
This issues appears in v9, but not in git version. Let's bump a new version for it.
