### ISSUE TITLE
What are the default shadow values for GNOME?

### ISSUE THREAD

**Issue by flexagoon** [yilozt/rounded-window-corners#12]
I like this extension, but I want the shadows on all of my windows to be the same, which is not the case when I install this. What values should I set in shadow settings to make rounded window shadows exactly the same as normal window shadows?

Relevant: #11

**Comment by yilozt** [comment]
Seems it can be found in GTK project, I'm not sure yet: 

[https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/theme/Default/_common.scss#L4053](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/theme/Default/_common.scss#L4053)

**Comment by davidphilipbarr** [comment]
I think the libadwaita shadow is three (?) Box shadows layered to create a more complex depth effect, adw-gtk3 has a simplified version for performance but I think it's still two shadows, so currently the same shadow can't be recreated but something similar can probably be passable taking an approximate average of the default shadows?

**Comment by yilozt** [comment]
Yes, libadwaita / adw-gtk use multi shadow to draw windows shadow. Unfortunately, the shadow style of rounded corners window only support apply one shadow in `box-shadow` css property.  

Actually the shadow for rounded corners window is just a [`St.Bin`](https://github.com/yilozt/rounded-window-corners/blob/ded0930263f86e661937e1b66fb3b4112e81ba21/src/manager/rounded-corners-manager.ts#L160) actor with a single `box-shadow` css property which insert below window. Though we can apply css to `Clutter.Actor` by `St` library, it still not support apply multi shadow in `box-shadow`.

So we only can got a similar result to default Adwaita theme.

**Comment by davidphilipbarr** [comment]
These settings are not a million miles away from the default, based on some
eyeballing and the liadwaita css.
