### ISSUE TITLE
"window shadow" settings are broken.

### ISSUE THREAD

**Issue by Blisterexe** [yilozt/rounded-window-corners#122]
when i click on it it does nothing, to clarify the button i am talking about is this:
![image](https://user-images.githubusercontent.com/128065612/236600183-b703ee9d-2d67-4b0b-9827-34bbe832a992.png)
I am running a rx 6600 on fedora 38 using wayland.
Oh, and the shadow doesnt play nice with burn my windows or compiz window effects, which is the reason i am trying to disable it.

**Comment by vrmaurice** [comment]
Yup, I've got the same problem. Please fix.

**Comment by Microwave-WYB** [comment]
Manjaro running on 1080Ti here, same problem. Doesn't seem like a distro or hardware specific problem

**Comment by Microwave-WYB** [comment]
You can still adjust them in dconf editor though

**Comment by Blisterexe** [comment]
@Microwave-WYB where?

**Comment by Microwave-WYB** [comment]
> @Microwave-WYB where?

Install dconf editor from flatpak
```
flatpak install dconf
```
and the two keys you can edit are
```
/org/gnome/shell/extensions/rounded-window-corners/focused-shadow
```
and
```
/org/gnome/shell/extensions/rounded-window-corners/unfocused-shadow
```

**Comment by yilozt** [comment]
The `Gtk.CssProvider.load_from_data()` function has update prototype in newer version. Now this problem should has been fix.
