### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [yilozt/rounded-window-corners#130]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by AndreaScerra** [comment]
Did you manage to make it work somehow?

**Comment by momoRaza** [comment]
anyone get this working in 45?

**Comment by yochananmarqos** [comment]
@AndreaScerra @momoRaza No. Either we wait for the developer to make the necessary changes or a helpful volunteer can submit a PR for review.

**Comment by momoRaza** [comment]
OK, thanks.

**Comment by Radical4ever** [comment]
i hope this gets update soon, this extension is a must on my installation

**Comment by pierre-rs** [comment]
> i hope this gets update soon, this extension is a must on my installation

+1

**Comment by SteelEyeballSac1** [comment]
Anyone know if there is work on support yet?

**Comment by Neo-29** [comment]
+1 for support please.
This is one of the most important feature for gnome

**Comment by makidrone** [comment]
+1 please!

**Comment by martijk** [comment]
Let’s leave our thumbs up in the original comment and refrain from posting +1 comments, as that will send an email notification to everyone who has subscribed to this issue and it doesn’t add anything useful to resolve it.

**Comment by in4matix** [comment]
I have tried Gnome 45 and frankly I see no reason to upgrade from Ubuntu 22.04.3 LTS Gnome 42.9 to Gnome 45, which BTW is currently only available in two distro's with no LTS in the foreseeable future . As a matter of fact there are MANY reasons NOT to use Gnome 45. IMO it is stupid to keep upgrading to a new release that offers no feasible advantage over previous releases. And why Gnome made 43 platform runtime end-of-life is just plain stupid, trying to force upgrading.

**Comment by Neo-29** [comment]
> I have tried Gnome 45 and frankly I see no reason to upgrade from Ubuntu 22.04.3 LTS Gnome 42.9 to Gnome 45, which BTW is currently only available in two distro's with no LTS in the foreseeable future . As a matter of fact there are MANY reasons NOT to use Gnome 45. IMO it is stupid to keep upgrading to a new release that offers no feasible advantage over previous releases. And why Gnome made 43 platform runtime end-of-life is just plain stupid, trying to force upgrading.

don't be ridiculous tks

**Comment by veraguido** [comment]
+1 gnome looks like shite without this extension.

**Comment by aidanhadley** [comment]
How's it looking so far? I see that it was updated just a few days ago, but yet when i try if gives the `import declarations may only appear at top level of a module` error.

**Comment by Neo-29** [comment]
> How's it looking so far? I see that it was updated just a few days ago, but yet when i try if gives the `import declarations may only appear at top level of a module` error.

Just the translations.
See commits.

**Comment by Movisivi** [comment]
This extension is dead. No meaningful commits since GNOME 44 release

**Comment by makidrone** [comment]
I tried fixing it for Gnome 45 and the build system is so convoluted and hard to work with, I kinda just gave up. Gnome doesn't make it easy to debug extensions either. I wish gjs was a bit more standard and had better typescript support but imo, this project needs a bit of a refactor

**Comment by aidanhadley** [comment]
it actually looks like it's being updated! 9 hours ago, on #137 . very excited for it! thank you devs 🙏

**Comment by yochananmarqos** [comment]
Thanks @yilozt, it's working fine.

Folks whine and complain, yet no one can say thank you. Good grief.

**Comment by Aworldc** [comment]
confirmed the gnome-45-port branch works fine for me.

**Comment by mbeps** [comment]
Where is the Gnome 45 branch? Has it been merged? If yes, I did not receive the update yet.

**Comment by PussInScreen** [comment]
> Where is the Gnome 45 branch? Has it been merged? If yes, I did not receive the update yet.

Works on Fedora 39, just grab it from here; https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by PussInScreen** [comment]
> > Where is the Gnome 45 branch? Has it been merged? If yes, I did not receive the update yet.
> 
> Works on Fedora 39, just grab it from here; https://extensions.gnome.org/extension/1319/gsconnect/

Jesus Christ.. Consider me lost lads, I thought I was on another extension page.

Anyway, I might try take a go at getting gnome 45 support going for this, need it to possibly fix dark corners on steam adw-gtk3; https://github.com/tkashkin/Adwaita-for-Steam/issues/222
