### ISSUE TITLE
Update shell version support on extensions.gnome.org to Gnome Shell 45

### ISSUE THREAD

**Issue by PolyCatDev** [yilozt/rounded-window-corners#147]
### What is my proposal?
Update the extension on https://extensions.gnome.org/ to support Gnome Shell 45 so that users have an easy installation process.

### What did I do?
I compiled the code from source and manually installed the extension.

### The result:
Everything works as intended, at least from what I can see.

### What am I using?
Gnome 45.2 on Fedora Silverblue 39 (silverblue-main u-blue image).

**Comment by lavafroth** [comment]
+1

**Comment by czarcadian** [comment]
The silence on this is so odd

**Comment by benjamin051000** [comment]
Any updates on this? I miss this extension :(

**Comment by threddast** [comment]
+1

**Comment by leaf-penguin** [comment]
Looks like this update was rejected. The issues seem pretty small.

https://extensions.gnome.org/review/47995

**Comment by 3ibod** [comment]
yes please

**Comment by coolkys** [comment]
This is a duplicate of #145. Discussions about why RWC is not on Gnome extensions for Gnome 45 and more are already on there.
