### ISSUE TITLE
How to blacklist Ubuntu Desktop Icon?

### ISSUE THREAD

**Issue by bzizmza** [yilozt/rounded-window-corners#19]
I found that rounded window affects desktop icons on ubuntu too, can you tell me how I can blacklist it?

Image when desktop icon extension is enabled and disabled
![image](https://user-images.githubusercontent.com/89899836/183055983-1de69a27-4b49-4599-83d4-31175412e952.png)
![image](https://user-images.githubusercontent.com/89899836/183056056-0a875d36-b0ec-4743-9ed5-9b0fa6e57e11.png)

You can see the angle
![image](https://user-images.githubusercontent.com/89899836/183055730-38af7f0a-daec-450b-9ce6-6ab1fe1a3d33.png)

**Comment by yilozt** [comment]
Add `gjs` to blacklist should solve this problem.

**Comment by yilozt** [comment]
Reproduce this issue when install [DING](https://gitlab.com/rastersoft/desktop-icons-ng) in my system. I will force disable rounded effect for it.

![image](https://user-images.githubusercontent.com/32430186/183072201-787eb3bb-b127-4557-9655-13d2a198289e.png)

**Comment by yilozt** [comment]
Should be fix in commit [cadf00f](https://github.com/yilozt/rounded-window-corners/commit/cadf00f13766674d1f3abbe10de29dbb509ec744)

**Comment by yilozt** [comment]
Confirm it has been fix in Ubuntu 22.04, the edge of desktop icon grid of DING has gone:

[Screencast from 08-05-2022 12_36_25 PM.webm](https://user-images.githubusercontent.com/32430186/183079634-84fb2adc-af59-47dc-82a4-c9866f6135ef.webm)
