### ISSUE TITLE
Gnome Tweaks corners are not rounded

### ISSUE THREAD

**Issue by marcinjahn** [yilozt/rounded-window-corners#23]
Somehow the extension has no effect on the Gnome Tweaks app.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/10273406/183245110-c7620d14-3d8e-44f5-8bfa-8cabf43e8a65.png)

**Comment by yilozt** [comment]
Check `Skip LibHandy Applications` in preferences pages:

https://user-images.githubusercontent.com/32430186/183245318-ce01425b-9c78-4b16-b69c-8dd8c650d5ab.mp4

**Comment by marcinjahn** [comment]
@yilozt You're right, that helped, thanks!
