### ISSUE TITLE
`meta_context_notify_ready: assertion 'priv->state == META_CONTEXT_STATE_STARTED || priv->state == META_CONTEXT_STATE_RUNNING' failed`

### ISSUE THREAD

**Issue by peterlobster** [yilozt/rounded-window-corners#25]
Noticed this error in my logs on a clean shell restart (`alt` + `F2` -> `r`) with only your plugin installed, no user themes either. Only happens with this plugin installed and enabled.

OS: Gentoo - 5.19.0
GNOME: 42.3.1

```shell
$ journalctl -r /usr/bin/gnome-shell
Aug 06 11:38:25 localhost gnome-shell[1707]: Registering session with GDM
Aug 06 11:38:25 localhost gnome-shell[1707]: GNOME Shell started at Sat Aug 06 2022 11:38:23 GMT-0700 (PDT)
Aug 06 11:38:23 localhost gnome-shell[1707]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 06 11:38:23 localhost gnome-shell[1707]: meta_context_notify_ready: assertion 'priv->state == META_CONTEXT_STATE_STARTED || priv->state == META_CONTEXT_STATE_RUNNING' failed
Aug 06 11:38:23 localhost gnome-shell[1707]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
Aug 06 11:38:23 localhost gnome-shell[1707]: Will monitor session 3
Aug 06 11:38:23 localhost gnome-shell[1707]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 06 11:38:22 localhost gnome-shell[1707]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 06 11:38:22 localhost gnome-shell[1707]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
```

Disabling the plugin (and restarting the GNOME shell), makes the error go away.
```
Aug 06 11:45:52 localhost gnome-shell[1707]: Registering session with GDM
Aug 06 11:45:52 localhost gnome-shell[1707]: GNOME Shell started at Sat Aug 06 2022 11:45:49 GMT-0700 (PDT)
Aug 06 11:45:50 localhost gnome-shell[1707]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 06 11:45:49 localhost gnome-shell[1707]: Will monitor session 3
Aug 06 11:45:49 localhost gnome-shell[1707]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 06 11:45:48 localhost gnome-shell[1707]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 06 11:45:48 localhost gnome-shell[1707]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
```

**Comment by yilozt** [comment]
I don't know how / why this error appears, it still exists even I try to comment all lines in `enable ()` of this extensions:

https://github.com/yilozt/rounded-window-corners/blob/838ffebfe8ac3167b1e8af207797f4b1d06da160/src/app.ts#L52

**Comment by peterlobster** [comment]
@yilozt I just started doing GTK-based development, but I'll ask around if someone can point out the problem, and I'll send whatever they say along...

**Comment by peterlobster** [comment]
@yilozt This might be helpful? https://gjs.guide/extensions/development/debugging.html#gjs-console

**Comment by yilozt** [comment]
Give up... I still don't have any idea to solve this issue.

**Comment by peterlobster** [comment]
@yilozt I'm working on it. I'm talking to a few of the GNOME developers on Matrix. I think we're making progress.

**Comment by yilozt** [comment]
Comfirmed that [ES Modules](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/ESModules.md) occurs this error. I don't think it is a `bug`, because it is not effect user experience.

Maybe I should stop use ES modules in extensions, it can stop this error message.

**Comment by yilozt** [comment]
This is a example extensions that uses ES Modules, it can emit this error message: [test@extensions.shell-extension.zip](https://github.com/yilozt/rounded-window-corners/files/9280976/test%40extensions.shell-extension.zip)
 
This is normal extensions that will not emit error message: [test@extensions.shell-extension.zip](https://github.com/yilozt/rounded-window-corners/files/9280993/test%40extensions.shell-extension.zip)
 
This example extensions even no nothing, it just print something to log:

```javascript
class Extension {
    enable() {
        log ('Extension Enabled')
    }
    disable() {
        log ('Extension disabled')
    }
}

function init () {
    return new Extension()
}
```

**Comment by peterlobster** [comment]
@yilozt WOW! Great work! ...and thank you for taking the time to debug and share that.

I had hit a similar crux yesterday, but hadn't hit on the ESM modules, but I guess it makes sense. Interestingly, I was told yesterday (on the GNOME Matrix) that eventually the GNOME Shell will move to ESM (in 43 or 44).
