### ISSUE TITLE
Restore sharp corners in window maximized state.

### ISSUE THREAD

**Issue by rashidi77** [yilozt/rounded-window-corners#3]
I think sharp corners should be restored in window maximized state just like the default Gnome apps.

Here is how they look now in maximized windows, I don't think they look good: 
![Screenshot from 2022-07-31 09-50-06](https://user-images.githubusercontent.com/93915281/182009242-c434d19f-a2c3-4f00-9bf6-de72ec153ef8.png)
![Screenshot from 2022-07-31 09-50-01](https://user-images.githubusercontent.com/93915281/182009244-737ede6c-d77b-42db-9a2d-abba0d412129.png)
![Screenshot from 2022-07-31 09-49-35](https://user-images.githubusercontent.com/93915281/182009247-c82427f3-97f1-41a8-8152-93d0f7049f4b.png)
![Screenshot from 2022-07-31 09-49-27](https://user-images.githubusercontent.com/93915281/182009249-893d2033-70fa-4915-9055-b565571d1b60.png)

**Comment by rashidi77** [comment]
I am on Gnome 43 if it matters. Mutter version 43.alpha.

**Comment by yilozt** [comment]
Disable `Keep Rounded Corners When Maximized` in preferences pages. It will disable rounded corners when maximized,

![image](https://user-images.githubusercontent.com/32430186/182010538-9b5c4e9c-633f-4f51-ba0d-4fc1128ba1b5.png)

**Comment by yilozt** [comment]
Maybe I should disabled this option by default.

**Comment by rashidi77** [comment]
Oh the issue was with discoverability then.
