### ISSUE TITLE
On resume, overview is broken (Fedora 36)

### ISSUE THREAD

**Issue by jmaris** [yilozt/rounded-window-corners#31]
Issue: when resuming from sleep, if I go into the shell overview, the overview crashes. The desktops are not shown and the overview freezes in place.

running `journalctl -r /usr/bin/gnome-shell` gets the following output

`-- Boot 68023ceb39e445608917d4ddaf0091ad --
Aug 09 16:15:39 homestead audit[4608]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=4608 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event4' (13,68): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event6' (13,70): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event7' (13,71): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event9' (13,73): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event11' (13,75): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event10' (13,74): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event1' (13,65): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event0' (13,64): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event2' (13,66): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:39 homestead gnome-shell[4608]: Could not release device '/dev/input/event5' (13,69): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Aug 09 16:15:38 homestead gnome-shell[4608]: #1   559643f66568 i   file:///var/home/jmaris/.local/share/gnome-shell/extensions/rounded-window-corners@yilozt/manager/rounded-corners-manager.js:318 (12afe97bb380 @ 17)
Aug 09 16:15:38 homestead gnome-shell[4608]: #0   559643f665f0 i   file:///var/home/jmaris/.local/share/gnome-shell/extensions/rounded-window-corners@yilozt/manager/rounded-corners-manager.js:561 (12afe97bb880 @ 40)
Aug 09 16:15:38 homestead gnome-shell[4608]: == Stack trace for context 0x55963ca0e640 ==
Aug 09 16:15:38 homestead gnome-shell[4608]: Object .MetaWindowActorWayland (0x55963dbbf4e0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using s>
Aug 09 16:15:38 homestead gnome-shell[4608]: #1   559643f66568 i   file:///var/home/jmaris/.local/share/gnome-shell/extensions/rounded-window-corners@yilozt/manager/rounded-corners-manager.js:318 (12afe97bb380 @ 17)
Aug 09 16:15:38 homestead gnome-shell[4608]: #0   559643f665f0 i   file:///var/home/jmaris/.local/share/gnome-shell/extensions/rounded-window-corners@yilozt/manager/rounded-corners-manager.js:561 (12afe97bb880 @ 40)
Aug 09 16:15:38 homestead gnome-shell[4608]: == Stack trace for context 0x55963ca0e640 ==
Aug 09 16:15:38 homestead gnome-shell[4608]: Object .MetaWindowActorWayland (0x55963dbbf840), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C`

**Comment by yilozt** [comment]
Are you using this extensions together with `Burn My Window`?

**Comment by jmaris** [comment]
This is the exact issue, sorry for the duplicate issue request, I forgot I had BMW installed

Cheers!

**Comment by yilozt** [comment]
#14 has been fix in release v5, you can upgrade this extensions.
