### ISSUE TITLE
Spotify isn't rounded (but everything else is)

### ISSUE THREAD

**Issue by GabePoel** [yilozt/rounded-window-corners#34]
![Spotify](https://user-images.githubusercontent.com/15686127/184177101-e122c8f9-faa6-490d-88d6-d0801dc95ef1.png)

See image above. Spotify's corners aren't getting rounded. But, the corners for every other window still are. This is the flatpak version run on Silverblue. But, I saw the same effect running the .deb via distrobox.

For some reason, clicking "Add Window" in the blacklist options causes the corners to become rounded even without selecting any window. I can then "X" out of the blacklist selection and the rounding remains. ¯\\\_(ツ)\_/¯

![Blacklist](https://user-images.githubusercontent.com/15686127/184178066-20c12940-bdb4-47e1-8e86-7946f04b6f93.png)

**Comment by sidevesh** [comment]
Definitely weird but I can confirm this happens not just for Spotify but all Chromium windows,
doing the Add Window and X routine fixes the rounded corners on all of them at once.

**Comment by yilozt** [comment]
It is fixed in commit [39aa93e](https://github.com/yilozt/rounded-window-corners/commit/39aa93e9d8235f53bc8a43923a371d08198a3667).
