### ISSUE TITLE
Breaks wobbly windows drop shadows on some apps

### ISSUE THREAD

**Issue by ryanfelder** [yilozt/rounded-window-corners#37]
This extension seems to cause drop shadow artifacts on some apps if the compiz-like wobbly windows extension is enabled.

Here's a video that I hope helps

https://user-images.githubusercontent.com/7475484/185196515-bf3d38e9-9d4e-42ff-90f5-acbab44e78dd.mp4

**Comment by yilozt** [comment]
@ryanfelder, maybe we can add an option to  hide shadow when move & resize window?

**Comment by ryanfelder** [comment]
For now, since this only seems to break Firefox, I have just added Firefox to my blacklist.

**Comment by yilozt** [comment]
The broken drop shadow is draw by this extensions, so it will not be used wobbly effect by `Compiz window effect`. I try to apply wobbly effect to drop shadow, but the result looks bad.

PR #60 can hide broken drop shadow when you move/resize window, but I don't know weather you really need this features.

**Comment by ryanfelder** [comment]
Thank you for looking into this but i dont need it that badly. Please feel
free to close this issue.
