### ISSUE TITLE
Error when installing from gnome extension website

### ISSUE THREAD

**Issue by joko-porolto** [yilozt/rounded-window-corners#38]
Technical details:

The settings of extension rounded-window-corners@yilozt had an error:
```
SyntaxError: expected expression, got '.'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by nickpolet** [comment]
I'm also getting this error. 

Ubuntu 20.04

**Comment by yilozt** [comment]
@nickpolet , this extensions only works in gnome 40+, but this extensions can works in Ununtu 20.04 because the version of gnome-shell im Ubuntu 20.04 is 3.36:

[https://packages.ubuntu.com/search?keywords=gnome-shell&searchon=names&suite=all&section=all](https://packages.ubuntu.com/search?keywords=gnome-shell&searchon=names&suite=all&section=all)

**Comment by joko-porolto** [comment]
@yilozt forgot to mention that I'm using ubuntu 20.04

**Comment by yilozt** [comment]
> this extensions only works in gnome 40+, but this extensions can works in Ununtu 20.04 because the version of gnome-shell im Ubuntu 20.04 is 3.36

this extensions only works in gnome 40+, but this extensions **can't** works in Ununtu 20.04 because the version of gnome-shell im Ubuntu 20.04 is 3.36

Very sorry for wrong typo, this extensions have not supported Ubuntu 20.04 yet. @nickpolet  @joko-porolto
