### ISSUE TITLE
Artifacts on overview after dragging windows.

### ISSUE THREAD

**Issue by jntdofe** [yilozt/rounded-window-corners#39]
After dragging a window on the overview it creates an artifact border on the bottom right of the window.

[video.webm](https://user-images.githubusercontent.com/73024442/185706673-ed7e7c90-c5e6-4969-b892-a3ac74749c09.webm)

it works both moving the window to other workspace or releasing it on the same workspace.

Edit: Extension Version 5, Fedora 36, Shell 42.3, Wayland, AMD integrated graphics.

**Comment by Nereboss** [comment]
Similar things happen when swapping from one workspace to another. All applications which are not minimized have a similar artifact border, all application that were minimized when opening the overview work correctly. When hovering over an application the artifact diappears.

Fedora 36, Gnome 42.4, Wayland, Intel integrated graphics
![image](https://user-images.githubusercontent.com/105795397/185965873-52e4bce7-05dd-4a9e-9f23-363458981421.png)

**Comment by AngleSideAngle** [comment]
Exact same behavior as Nereboss
Note that this only affects apps that the extension is enabled for.
Fedora 36, Gnome 42.4, Wayland

**Comment by sidevesh** [comment]
Same here, for me those artifacts also show up sometimes when I switch between workspaces on overview screen,
Arch, Gnome 42.4, X11

**Comment by sevenzerotwo** [comment]
![Screenshot from 2022-09-02 19-41-37](https://user-images.githubusercontent.com/80304158/188147498-c228dd98-4d67-4677-8cf2-c7cd7646ac65.png)
Same here, same behavior as sidevesh and Nereboss
Ubuntu 22.04.1, GNOME 42.2, X11

**Comment by yilozt** [comment]
Should be fixed in [a1d7ace](https://github.com/yilozt/rounded-window-corners/commit/a1d7aced6db77e8b65ca9710290ebb7f72100f87), now artifacts should disappear when drag window & change workspace in overview:

[录屏 2022年09月04日 18时53分13秒.webm](https://user-images.githubusercontent.com/32430186/188309845-09eb7766-4b2d-4afb-b985-2fc9693733e4.webm)

[录屏 2022年09月04日 18时53分51秒.webm](https://user-images.githubusercontent.com/32430186/188309846-0b070ca3-eb4f-430c-b96c-d603ca671ca4.webm)

**Comment by yilozt** [comment]
There is still artifacts when type something in overview:

[录屏 2022年09月04日 21时33分40秒.webm](https://user-images.githubusercontent.com/32430186/188316341-8ff3c16d-3224-4a18-80de-19230881fa66.webm)

**Comment by sidevesh** [comment]
I don't see the glitch happening when typing something in overview on my system,
is the new commit which fixed the previous two glitches pushed to gnome extensions ?
