### ISSUE TITLE
Performance issues on maximized browsers

### ISSUE THREAD

**Issue by avanishsubbiah** [yilozt/rounded-window-corners#44]
With this extension whenever a browser window is maximized (tested with Firefox and Edge) there is performance issues with stuttering in the browser. These issues disappear when the window is no longer maximized. Specifically this was tested by running https://www.testufo.com/ . When the browser is windowed it yields a solid 60fps and when maximized it drops down to 50-51 fps from stutters. This does not occur when the extension is disabled.

**Comment by yilozt** [comment]
I have try to remove rounded corners effect when window is maximized in #45, you can download the [extensions pack](https://github.com/yilozt/rounded-window-corners/suites/8117540945/artifacts/351175948) from [https://github.com/yilozt/rounded-window-corners/actions/runs/2983058715](https://github.com/yilozt/rounded-window-corners/actions/runs/2983058715), and install it by

```
gnome-extensions install rounded-window-corners@yilozt.shell-extension.zip
```

Sorry that I can't reproduce this issue, I am using intel driver and but it always yields 60 fps both in XOrg and Wayland session.

Feel free to leave a comment if #45 have not fix this problem.

**Comment by avanishsubbiah** [comment]
> I have try to remove rounded corners effect when window is maximized in #45, you can download the [extensions pack](https://github.com/yilozt/rounded-window-corners/suites/8117540945/artifacts/351175948) from https://github.com/yilozt/rounded-window-corners/actions/runs/2983058715, and install it by
> 
> ```
> gnome-extensions install rounded-window-corners@yilozt.shell-extension.zip
> ```
> 
> Sorry that I can't reproduce this issue, I am using intel driver and but it always yields 60 fps both in XOrg and Wayland session.
> 
> Feel free to leave a comment if #45 have not fix this problem.

That seems to have fixed the issue for me Firefox and Edge when maximized no longer drop frames with that version of the extension. Nice!
