### ISSUE TITLE
Padding does'not apply to corners

### ISSUE THREAD

**Issue by oae** [yilozt/rounded-window-corners#52]
Borders are not removed from corners when I add padding. 

![Peek 2022-09-08 13-51](https://user-images.githubusercontent.com/1043714/189104294-00ff6f02-4b7b-4475-a5c3-94c96f4775db.gif)

**Comment by yilozt** [comment]
Fixed now:

https://user-images.githubusercontent.com/32430186/189108892-1df66212-4d8e-455d-98d5-88c8fdafea76.mp4
