### ISSUE TITLE
Not supported for Fedora 37

### ISSUE THREAD

**Issue by MaliciousXatt** [yilozt/rounded-window-corners#53]
Hi, 
It might be a bit quick already.
The rounded-window-corners does not work for Fedora 37.

**Comment by yilozt** [comment]
It can run in gnome 43, you can edit `~/.local/share/gnome-shell/extensions/rounded-window-corners@yilozt/metadata.json` like this:

```json
{
  "name": "Rounded Window Corners",
  "description": "Add rounded corners for all windows",
  "uuid": "rounded-window-corners@yilozt",
  "version": "5",
  "url": "https://github.com/yilozt/rounded-window-corners",
  "shell-version": ["40", "41", "42", "43"]
}
```

Then restart gnome-shell, it should works.

**Comment by MaliciousXatt** [comment]
Great! it works, thank you.
