### ISSUE TITLE
Border is drawn inside the windows

### ISSUE THREAD

**Issue by lonssi** [yilozt/rounded-window-corners#56]
If the extension is turned off, the window border seems to be drawn outside the window boundary. When the extension is turned on, the border seems to be drawn inside the window, which makes the usable area of the window slightly smaller. This creates a visual difference to the default look. Could the borders be drawn outside the window boundary?

Extension turned off:
![extension_off](https://user-images.githubusercontent.com/16960005/189366919-8fca2713-584e-4c8e-802b-5a887cdc6d4d.png)

Extension turned on (border size is 1px):
![extension_on](https://user-images.githubusercontent.com/16960005/189366930-6404d632-aa29-4bdb-9bb3-9b1e2bf21f3e.png)

**Comment by RomanKode** [comment]
Check your padding settings. (Mine cuts 2px)
![Screenshot from 2022-09-12 18-34-07](https://user-images.githubusercontent.com/70252656/189778696-ff79b6a1-a1f1-4b64-b5a6-676e6c0d25ec.png)

**Comment by lonssi** [comment]
@RomanKode I tried playing with the padding and border settings but couldn't get a result that would look exactly like libadwaita style. So I still think reaching an exact libadwaita-look would require that the border would be drawn outside the window.

**Comment by yilozt** [comment]
This extensions is currently drawing border inside bounds of clip area of rounded corners. I will try to add an option to let extensions draw border outside of window.

**Comment by RomanKode** [comment]
Check if "Ignore Libadwaita" is switched on, if it is, turn it off, by turn it it off you let the extension handle the radius and padding of the window. This will make all windows look consistent.

If I'm not mistaken the the window constraints are at the very border of the window, you can also set the padding to "0" so it does not cut anything and it leaves it original.(unless the extension has a hard coded padding of 1px)

**Comment by yilozt** [comment]
Implemented in #63, @lonssi
