### ISSUE TITLE
Non-removable entry in desktop right-click menu

### ISSUE THREAD

**Issue by christopher-l** [yilozt/rounded-window-corners#59]
![Screenshot from 2022-09-10 16-22-04](https://user-images.githubusercontent.com/1208506/189487644-e17ad798-dd02-4cbb-9168-8cc27974e4d0.png)
For me, there is not really any reason to access the settings of this extension more often than those of any other one, so I'd like this menu entry to be optional or not there at all.

**Comment by yilozt** [comment]
I will add an options to make this entry removable.

**Comment by christopher-l** [comment]
Wow, that was fast!
Thank you so much. :)
