### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [yilozt/rounded-window-corners#61]
@yilozt
https://hosted.weblate.org/projects/rounded-window-corners/rounded-window-corners/#information
Says LGPL
whereas
https://github.com/yilozt/rounded-window-corners/blob/main/LICENSE
is GPL

This can be changed to GPLv3-or-later in
https://hosted.weblate.org/settings/rounded-window-corners/rounded-window-corners
:)

**Comment by comradekingu** [comment]
Closing as fixed :)

**Comment by yilozt** [comment]
It's my wrong, now it is fixed. Thanks very much!
