### ISSUE TITLE
Shadow of apps underneath is rendered on the very top when switching workspaces

### ISSUE THREAD

**Issue by marcinjahn** [yilozt/rounded-window-corners#64]
Sometimes, when multiple windows are open on a workspace, switching between workspaces leaves shadows of the windows in front of other windows. I captured this on the recording below.

[Kooha-2022-09-14-14-19-37.webm](https://user-images.githubusercontent.com/10273406/190152002-f7b4e1c0-76c9-46fe-9109-63e55f3d3f1e.webm)

I have a maximized Firefox windows, a Calendar (and Kooha to record the screen). When I switch between workspaces, you can see shadow artifact left by Calendar and Kooha on top of Firefox.

**Comment by yilozt** [comment]
Duplicates with #55, it has been fixed.
