### ISSUE TITLE
Gnome 43 support?

### ISSUE THREAD

**Issue by jonseppanen** [yilozt/rounded-window-corners#66]
Seeing as gnome 43 has been released, any chance of a version bump?

**Comment by yilozt** [comment]
I have try to run this extensions in gnome 43 beta, it works, but the window will looks very blurry and terrible if there is more than two workspaces in overview. This problem only occurs in gnome 43 beta, I don't know this problem whether still occurs in released version of gnome 43.

If this problem still occurs in official gnome 43, it means that there is a bug of this extensions.

**Comment by CharlieQLe** [comment]
Running on Fedora Silverblue 37 Prerelease, which has the full release of GNOME 43, and this bug still occurs. On my multi-monitor setup, it is only blurry on the primary monitor.

**Comment by yilozt** [comment]
We can close this issues because blurry windows in overview has been fixed. This extensions can works in gnome 43 now.
