### ISSUE TITLE
Strong edge highlighting in screenshots

### ISSUE THREAD

**Issue by un-couteau** [yilozt/rounded-window-corners#67]
![image](https://user-images.githubusercontent.com/65289168/192054389-c95f78ae-b828-4d27-8048-15e2e357f223.png)

gnome-screenshot does this:
![image](https://user-images.githubusercontent.com/65289168/192054642-68760cbb-48c8-431c-a958-fe73f1f5c6f1.png)

And in fact I see it this way (as in obs):
![image](https://user-images.githubusercontent.com/65289168/192054707-04b6867b-e7be-4f94-99c0-40713eb35fcb.png)

**Comment by yilozt** [comment]
This is the screenshot by using the builtin tools of gnome shell, I open it with eog:

![图片](https://user-images.githubusercontent.com/32430186/192474065-57831b3f-2069-4b7f-a695-6d4c3d6393fc.png)

You can see there is an transparent area in this picture, maybe there is some problem relative with the screenshot tools:

![图片](https://user-images.githubusercontent.com/32430186/192477234-2ef2653a-1d8c-447d-84c8-8f367e5d53e5.png)

![图片](https://user-images.githubusercontent.com/32430186/192477342-0d01cff0-8977-4c8c-b67c-e4801f770dfc.png)

**Comment by un-couteau** [comment]
![image](https://user-images.githubusercontent.com/65289168/197642075-7c630977-aff4-4bda-afd7-6baeebf54b36.png)
When you make a screenshot of a separate window, the bug is still there
{To get the bug, right-click on the picture and select "Open Image in New Tab"
although even so, you can see that in the corners of the selection is thinner and more prominent (which in a full-screen screenshot was not noticed)}
![image](https://user-images.githubusercontent.com/65289168/197642506-0f32b887-8888-4120-b96f-051644f8dfb3.png)
![image](https://user-images.githubusercontent.com/65289168/197643029-88cd3c6a-5ce9-4eec-af59-cdf8a67130b1.png)


![image](https://user-images.githubusercontent.com/65289168/197642297-177165fa-f4d2-4583-b71f-84bb88b677fe.png)
And there is no such thing with a full screen

![image](https://user-images.githubusercontent.com/65289168/197642593-5ce9e84f-b7e6-433c-8265-7c86c56bbedc.png)
{As you can see everything is perfect here}

**Comment by yilozt** [comment]
Hi @un-couteau ,I can confirm this bug, thanks to report it.

If I set the border width to a positive value, there is no strange highlighting when make screenshots to separate window.

But if I set the border width to a negative value, this bug occurs. I will try to fix it later.

**Comment by yilozt** [comment]
Should be fixed.

when set border width to positive value:

![图片](https://user-images.githubusercontent.com/32430186/197916861-b623197d-328e-4812-ae34-d91ce7be3378.png)

when set border width to negative value:

![图片](https://user-images.githubusercontent.com/32430186/197917140-d6a795d4-6cfd-47d4-b7eb-47adf155c2a7.png)

If right click on image and open it in new tab, the highlighting color should not occurs in corners of window. you can test it by download extensions pack in Github Actions if you like.

**Comment by un-couteau** [comment]
Oh, man.
You're so cool.
Now it's not a shame to share screenshots
thank you for doing such a great job
it's not like kde rounded corners which is terrible
![Снимок экрана от 2022-10-27 03-03-26](https://user-images.githubusercontent.com/65289168/198147328-fd8999e1-1736-4ecb-a63e-87f0301fe14d.png)
