### ISSUE TITLE
Small artifacts in overview mode

### ISSUE THREAD

**Issue by bragefuglseth** [yilozt/rounded-window-corners#8]
I use GNOME 42.3 on a 1440p monitor. The rounded corners look good except for when I'm in the overview and have a dark theme applied. They seemingly get a grey "artifact" in the places where the rounded corners have been applied by the extension. This does not happen with proper LibAdwaita applications, only ones where the extension is in use. Also, this only seems to be visible when the apps are in dark mode or have a dark-ish appearance.

## To reproduce

1. Switch an app using the extension to a dark theme, or use one that has dark colors already (like Discord or Spotify)
2. Press the super key and enter overview mode

## Screenshots

![Screenshot from 2022-08-03 11-01-03](https://user-images.githubusercontent.com/91388039/182570923-6ccd5998-2231-4f2d-8d73-f29226833418.png)
*How the bottom rounded corners of GIMP normally look*

![Screenshot from 2022-08-03 11-00-56](https://user-images.githubusercontent.com/91388039/182571058-bf7dd436-39a5-4721-b06a-989ffebfd625.png)
*How they look in overview mode*

![Screenshot from 2022-08-03 11-00-25](https://user-images.githubusercontent.com/91388039/182571461-0c4e4c35-af9c-460a-b691-7f261afa6d7e.png)
*The bottom corner of Celluloid, dark mode, in overview*

![Screenshot from 2022-08-03 11-01-49](https://user-images.githubusercontent.com/91388039/182571575-a8adfc96-173d-49a2-9242-a73200f56a32.png)
*The bottom corner of Celluloid, light mode, in overview*

**Comment by yilozt** [comment]
Seems like I have insert shadow above window container in overview wrongly. It can be fix in commit [6cb2120](https://github.com/yilozt/rounded-window-corners/commit/6cb212044f63f2226458ec5179fa0e0643961e8d)

**Comment by bragefuglseth** [comment]
Niiiice, that seems like the solution. Thank you for developing this!
