### ISSUE TITLE
Superelliptical shape of corners

### ISSUE THREAD

**Issue by YuraIz** [yilozt/rounded-window-corners#9]
My suggestion is use [superellipses](https://en.wikipedia.org/wiki/Superellipse) instead of circles to crop corners

That corners looks more smooth and used in macos, ios and some physical devices

Here's an example screenshot with edited fragment shader
![Example screenshot](https://user-images.githubusercontent.com/63008755/182591389-7c75b938-522d-41c3-97f3-d9aa3725a6fc.png)

Here's screenshots with different superellipses
![Superellips 1](https://user-images.githubusercontent.com/63008755/182592567-096473ea-6de8-449a-8a2d-c9c157908416.png)

![Superellips 2](https://user-images.githubusercontent.com/63008755/182592554-0eca9bd0-57f1-4e01-aca2-298e400129f9.png)
regular circle is subset of superellipse
![Circle](https://user-images.githubusercontent.com/63008755/182592518-6de941f9-253e-4a24-81a9-b11cd5db2b27.png)

In settings it can be like corner smoothing parameter in figma
![Smoothing](https://user-images.githubusercontent.com/63008755/182594198-1c529210-2d7e-4025-ba2f-895a41c7b9dc.png)

I can finish this by myself if it's useful feature

**Comment by yilozt** [comment]
It's awesome feature! please open pull request when it is ready.
