### ISSUE TITLE
mutter-43.1: broke corners

### ISSUE THREAD

**Issue by frosth555** [yilozt/rounded-window-corners#90]
After mutter update few apps like gnome-terminal, firefox, chrome... got broken:
![Zrzut ekranu z 2022-11-04 21-30-30](https://user-images.githubusercontent.com/22305379/200070992-0b5f30b8-e077-4383-b721-ad82a227c06b.png)
it's happened on adwaita aswell.

the root of problem is here:
[first bad commit](https://gitlab.gnome.org/GNOME/mutter/-/commit/6cbc5180892280bb657f7cb9c6d018f8f4885f2b)
after revert it issue dissapear

**Comment by suhasofficial** [comment]
Same thing happend with me , i was using  this extension after several try on installing mutter-rounded in arch

**Comment by kherock** [comment]
Mine doesn't look as broken as the screenshot but it seems like rounded corners aren't functional for Wayland windows. For me, the window shadows also have clipping artifacts in some corners that appear normal in screenshots.

**Comment by frosth555** [comment]
In my case wayland or no doesn't matter, firefox(wayland) lost bottom corners aswell, and I've changed dimension of terminal to higlight the problem.

**Comment by frosth555** [comment]
I don't want to whine "fix-gnome-43.1-wayland-client" branch works, but I have another issue, there is small lag before corners became rounded:

https://user-images.githubusercontent.com/22305379/200309145-f77032f1-be9c-4ace-b888-1f27a4e6d1b5.mp4

don't know if it possible to fix easy, but just want to notice

**Comment by yilozt** [comment]
@frosth555, Thanks to test the PR , I will try to fix this problem before merge it.

**Comment by frosth555** [comment]
All thanks to you, with this extension gnome looks amazing. 
+1 to wait with merging cause fix-gnome-43.1-wayland-client brings this lag to 42.x

**Comment by yilozt** [comment]
Now the lag should be disappeared.

**Comment by frosth555** [comment]
yes, I see no lags. Thanks a lot. 
no regression on 42.x aswell
