### ISSUE TITLE
GS-43.1- firefox's Picture-in-Picture videos lose content after fullscreen and back

### ISSUE THREAD

**Issue by frosth555** [yilozt/rounded-window-corners#92]
again gnome 43.1(wayland), not happened before commit: "fix broke corners..." 
not only fullscreen is affected, any tiled PIP window loses content right after untiled

from mutter side the culprit is: https://gitlab.gnome.org/GNOME/mutter/-/commit/909616b20876478bc56932cd18c8e85e982645f6
can't revert to check it. but mutter before this commit worked normal with v9

[Nagranie ekranu z 2022-11-08 19-26-11.webm](https://user-images.githubusercontent.com/22305379/200652425-af28d001-f825-4e48-9ad0-636ea20c848e.webm)

**Comment by yilozt** [comment]
It should have been fixed in commit [`dbf814c`](https://github.com/yilozt/rounded-window-corners/commit/dbf814c6ec206b0035f3db2b5b6435b7f07007c5):

[录屏 2022-11-09 10-58-42.webm](https://user-images.githubusercontent.com/32430186/200727066-b27b83ce-8651-410e-b2ef-5096c83cfe1b.webm)

**Comment by frosth555** [comment]
yupi, that works indeed :)
thanks again
