### ISSUE TITLE
Round maximized and tiled windows in overview

### ISSUE THREAD

**Issue by sidevesh** [yilozt/rounded-window-corners#93]
Can we round the corners of maximized and tiled windows in overview, even if they are set to not have rounded corners in options ?
![image](https://user-images.githubusercontent.com/17254413/201505542-0f8c3a4e-c3aa-41b4-80b6-a92715bf320a.png)

These stick out in overview with sharp corners and this would make the rounded windows aesthetic fully consistent.
Can this be implemented by this extension ?

**Comment by sidevesh** [comment]
I have tried the rounded-all-windows-in-overview branch locally on my system and it works perfectly fine, can you push it as an update please ? Thanks!

**Comment by sidevesh** [comment]
Hi, any reason the above PR has not been merged and released ? Its been working perfectly for me for months now.

**Comment by yilozt** [comment]
Hi, sorry for reply so lately. My plan is add a option to control radius of rounded corners of window in overview to make this feature more configurable. But I have no much time to finish it. (have to spend most time to finish my graduation design :( )I will try to finish it when I have free time.获取Outlook for Android

**Comment by sidevesh** [comment]
@yilozt while you are updating this for Gnome 45, can we please get this merged in ?
It's a really good addition to the overall effect and the overview looks really out of place without this option.

**Comment by sidevesh** [comment]
I have been testing this for almost half a year and can assure you this works perfectly and causes no issues,
an option to configure the radius would be great but it works perfectly fine even without it.

**Comment by sidevesh** [comment]
@yilozt were you able to take alook at rebasing https://github.com/yilozt/rounded-window-corners/compare/rounded-all-windows-in-overview and merging it in ?
