### ISSUE TITLE
How to disable desktop border on Ubuntu 22.04

### ISSUE THREAD

**Issue by orklann** [yilozt/rounded-window-corners#96]
As you can see in the screenshot, after restart Ubuntu 22.04, the desktop also has borders like other windows, how can I remove the desktop borders, can I set it in the blacklist?

![Screenshot from 2022-11-25 12-39-02](https://user-images.githubusercontent.com/5492042/203903141-2b39a0db-bd21-4a0c-adcb-356591740c10.png)

**Comment by yilozt** [comment]
Are you using some extensions to show icons on desktop (like DING)? Or using some live wallpaper applications?

**Comment by orklann** [comment]
Yes, I think I have added it to blacklist by this id `com.rastersoft.ding`, and restart this extention, and it works fine.

**Comment by orklann** [comment]
But after restart my computer, the desktop borders are still there. Any help?

**Comment by orklann** [comment]
I guest the id I put in blacklist was wrong, not `com.rastersoft.ding`?

**Comment by somepaulo** [comment]
Blacklist `gjs`. That's what runs all extensions, including desktop icons, which acts like a maximized window, so gets the border.

**Comment by orklann** [comment]
@somepaulo Thank you, it works by blacklist `gjs`.
