### ISSUE TITLE
Windows are being overcropped

### ISSUE THREAD

**Issue by ceiphr** [yilozt/rounded-window-corners#98]
Hello!

Here I have an unmaximized Firefox window. When I click the menu icon, the window is overcropped:

![Screenshot from 2022-12-05 13-19-54-obfuscated](https://user-images.githubusercontent.com/21004034/205712864-c35d47f8-7b93-42e4-843c-d9bdea0ab92f.png)

(email removed from menu for privacy)

I've also had this happen when simply launching the `gnome-terminal`.

Fedora 37, Gnome 43, Wayland.

Please let me know if you need anymore details!

**Comment by trbntwo** [comment]
I have the same problem, also Wayland didn't test it on X11. No difference with Nividia Drivers or integrated AMD Graphics. Also the Firefox theme has no impact is also with base Firefox.
Will edit when tested on X11

**Comment by frosth555** [comment]
weird thing is I can't repro this on arch, but fedora is affected. 
could you build the extension from git? it is similar to #92

**Comment by nikolowry** [comment]
^ @frosth555 I'm on Arch and have been experiencing this issue, happened recently last week after upgrades. I'll do a git build tomorrow prior to starting work

**Comment by ceiphr** [comment]
v10 fixes this for me! :tada:  Closing this issue. Lmk if any of you are still having this problem, I'll reopen the issue.
